### PR TITLE
Add self-chrooting capability, documentation and examples

### PR DESCRIPTION
**Pull request by mikhailnov**
Chroot into a separate directory to prevent access to /etc, /var, /home and other places with possibly sensitive information. This will prevent data leaks if there is a vulnarability that will allow arbitrary code execution in wsdd.

This approach is used in ROSA Linux: https://abf.io/import/wsdd

### CODE REVIEW

**Comment by christgau** [comment]
That's really a good proposal. I had this in mind for a future release but now it's already here 😉

There are some minor cosmetic changes I'm going to make to your PR but I need to find some time to make these and the merge. Nevertheless, thanks for your contribution.

**Comment by christgau** [comment]
I've made a few changes to the PR. Most notably the chroot-step has been moved a little more "down" with respect to the initialization steps of wsdd. It is now performed just before the packet handling starts but after interface addresses have been determined. At this point all required packages and according dependencies should be loaded. That way, you can chroot in an empty directory. This also simplifies the systemd unit files where it is sufficient to create an empty directory and remove it after execution. No need for copying libraries as long as the introduced self-chrooting feature is used. I've tested the changes under Fedora 30 with an empty root and it works as before.

Are the changes also useful for ROSA Linux?

**Comment by mikhailnov** [comment]
Sotty for late response. It seems reasonable to me, thank you. Hope that I understood correctly that `udp_srv = WSDUdpRequestHandler(interface)` does not do anything network-related and
```
def __init__(self, interface):
        self.interface = interface
```
will be the only executed code.

I will switch ROSA Linux package to this chrooting method when it becomes upstream.

**Comment by mikhailnov** [comment]
Thanks for merging. Just a small hint: `Co-authored-by:` field (https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) may be used in commits.

**Comment by christgau** [comment]
Thanks for pointing that out, I wasn't aware of this. Next time I'll do better.

**Pull request merged**
