### PR TITLE
Only start HTTPServer once for each listening address

### PR DESCRIPTION
**Pull request by emontnemery**

### CODE REVIEW

**Comment by christgau** [comment]
Thanks for the PR. 

Just to be sure that I understand the its purpose in the correct way: The PR solves the problem, that the HTTP server - and thus wsdd - will fail (likely with "address in use" or similar) in case there are multiple interfaces that share an IPv4 address? Is that correct? This problem should not occur with interfaces having the same IPv6 addresses. 

(I can't test that case, ATM).

**Comment by emontnemery** [comment]
> The PR solves the problem, that the HTTP server - and thus wsdd - will fail (likely with "address in use" or similar) in case there are multiple interfaces that share an IPv4 address

Yes, exactly.

**Comment by christgau** [comment]
Mh. I can figure out the following use-case, which I think is a rather strange one. 

Suppose your machine has two interface A and B with the same IPv4 address Z. This is strange anyway. IMO this only works if A and B are connected to different networks. Otherwise, ARP would be screwed up - again IMO. 

So, let's assume A and B are in fact connected to different networks. If you then start up wsdd, there should be two different sockets which multicast the Hello message to the network they are responsible for. In order to handle the resulting HTTP requests, there must be an HTTP server running for both interfaces. If the interfaces share an IPv4 address, there cant be two servers that bind to the same address (as you observed). However, if you bind only a single server to address Z how can you be sure that it serves the traffic on both sides? If you start wsdd with your patch on both A and B interfaces and if HTTP traffic arrives on interface B will it really be handled by the single HTTP server and successfully send replies via B? Or does the HTTP sent replies via A?

Could you please describe your use case a little or why it is necessary to run wsdd on a set of interfaces that share the same IPv4 address?

**Comment by emontnemery** [comment]
Right, it's two different networks.

My use case is a ppp tunnel, where ppp0 has the same address as the ethernet interface because routing is handled by Proxy ARP.

In my case it's not necessary to run wsdd on the ppp0 interface, so OK to close this PR if you think it just risks adding bugs and complexity.

>if you bind only a single server to address Z how can you be sure that it serves the traffic on both sides?
If you start wsdd with your patch on both A and B interfaces and if HTTP traffic arrives on interface B will it really be handled by the single HTTP server and successfully send replies via B? Or does the HTTP sent replies via A?

I can do some testing if you want?

**Comment by christgau** [comment]
Thanks for sharing your use case which sounds quite complex 😊

> In my case it's not necessary to run wsdd on the ppp0 interface, so OK to close this PR if you think it just risks adding bugs and complexity.

In principle, your patch looks fine regarding style and complexity. What I'm asking myself is if the patch works in every scenario. Suppose you run wsdd without options and your proposed patch, so it tries to use every interface (except lo) and assume further that ppp0 is enumerated first before, say, eth0. Then, wsdd announces your host on both ppp0 and eth0. Clients are likely to be on eth0. So they sent traffic to wsdd's HTTP server. However that one was `bind(2)`ed to the IPv4 address that ppp0 and eth0 share. I am absolutely unsure that the HTTP server socket will handle traffic both from ppp0 and eth0. It's very likely that it will handle only one interface. Maybe its ppp0 because it was enumerated first. However, which one is handles depends on the actual OS. In addition to this issue of receiving data from the right interface, sending will depend on the routing table. And it may result in the wrong outgoing interface. Binding the HTTP server sockets to an interface using `SO_BINDTODEVICE` may help (never used that one before). 

To put it in a nutshell: Will a single HTTP server socket that is "responsible" for several interfaces with the same IP handle the traffic for all interfaces it is responsible for in the correct way?

Aside from that technical issue: If you want wsdd to run only on a specific interface, then you can do so by specifying it on the according interface. 😉 In addition, I don't think that announcing yourself on ppp0, i.e. blowing packets to the dial-up network that leak your private IP and hostname, is a good thing.

> I can do some testing if you want?

Does the version with the patch from this PR work in your setup?

**Comment by emontnemery** [comment]
> To put it in a nutshell: Will a single HTTP server socket that is "responsible" for several interfaces with the same IP handle the traffic for all interfaces it is responsible for in the correct way?

> Does the version with the patch from this PR work in your setup?

The HTTP server socket is bound to an address though, and knows nothing of an interface. It's an interesting question, but this patch won't affect if the routing will work or not I think?
The only thing changed by the patch is that wsdd does not try to create multiple HTTP server sockets listening to the same address.

And sure, it is working fine both with and without the patch (if specifying the interface), so the routing is working fine.

> I don't think that announcing yourself on ppp0, i.e. blowing packets to the dial-up network that leak your private IP and hostname, is a good thing.

The ppp interface is thankfully not connecting to the public internet, it's connecting with some old equipment over a virtual serial link. This very old equipment really couldn't care less about Win10 shares though so your point is still valid. 😉

**Comment by emontnemery** [comment]
I'm closing this:
- My usecase is arcane
- The patch doesn't work correctly

**Pull request closed without merging**
